import os
import threading
from contextlib import contextmanager

import psycopg
from psycopg import sql


DATABASE_URL = os.environ.get(
    "DATABASE_URL",
    "postgresql://localhost/news_parser",
)

NEWS_SCHEMA = "news"
COMMENTS_SCHEMA = "comments"
STATISTICS_SCHEMA = "statistics"

SCHEMA_STATEMENTS = {
    NEWS_SCHEMA: (
        """
        CREATE TABLE IF NOT EXISTS posts (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            news_title TEXT NOT NULL,
            news_text TEXT NOT NULL,
            university_name TEXT NOT NULL,
            news_date TEXT NOT NULL,
            news_img BYTEA,
            deleted INTEGER NOT NULL DEFAULT 0
        )
        """,
    ),
    COMMENTS_SCHEMA: (
        """
        CREATE TABLE IF NOT EXISTS comments (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            post_id BIGINT NOT NULL,
            nick TEXT NOT NULL,
            text TEXT NOT NULL,
            created_at TEXT NOT NULL
        )
        """,
    ),
    STATISTICS_SCHEMA: (
        """
        CREATE TABLE IF NOT EXISTS post_views (
            post_id BIGINT NOT NULL,
            voter_id UUID NOT NULL,
            PRIMARY KEY (post_id, voter_id)
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS post_likes (
            post_id BIGINT NOT NULL,
            voter_id UUID NOT NULL,
            PRIMARY KEY (post_id, voter_id)
        )
        """,
    ),
}

_schema_lock = threading.Lock()
_initialized_schemas = set()


def initialize_schema(connection, schema_name):
    if schema_name not in SCHEMA_STATEMENTS:
        raise ValueError(f"Unknown database schema: {schema_name}")
    with _schema_lock:
        with connection.transaction():
            connection.execute(
                sql.SQL("CREATE SCHEMA IF NOT EXISTS {}").format(
                    sql.Identifier(schema_name)
                )
            )
            connection.execute(
                sql.SQL("SET LOCAL search_path TO {}").format(
                    sql.Identifier(schema_name)
                )
            )
            if schema_name not in _initialized_schemas:
                for statement in SCHEMA_STATEMENTS[schema_name]:
                    connection.execute(statement)
        _initialized_schemas.add(schema_name)


@contextmanager
def get_connection(schema_name):
    if schema_name not in SCHEMA_STATEMENTS:
        raise ValueError(f"Unknown database schema: {schema_name}")
    with psycopg.connect(DATABASE_URL) as connection:
        initialize_schema(connection, schema_name)
        connection.execute(
            sql.SQL("SET search_path TO {}").format(sql.Identifier(schema_name))
        )
        yield connection
